// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fulfillment

// OperationsClientActivateSubscriptionResponse contains the response from method OperationsClient.ActivateSubscription.
type OperationsClientActivateSubscriptionResponse struct {
	// placeholder for future response values
}

// OperationsClientDeleteSubscriptionResponse contains the response from method OperationsClient.DeleteSubscription.
type OperationsClientDeleteSubscriptionResponse struct {
// OperationLocationURI contains the information returned from the Operation-Location header response.
	OperationLocationURI *string
}

// OperationsClientGetSubscriptionResponse contains the response from method OperationsClient.GetSubscription.
type OperationsClientGetSubscriptionResponse struct {
	Subscription
}

// OperationsClientListAvailablePlansResponse contains the response from method OperationsClient.ListAvailablePlans.
type OperationsClientListAvailablePlansResponse struct {
	SubscriptionPlans
}

// OperationsClientListSubscriptionsResponse contains the response from method OperationsClient.NewListSubscriptionsPager.
type OperationsClientListSubscriptionsResponse struct {
	SubscriptionsResponse
}

// OperationsClientResolveResponse contains the response from method OperationsClient.Resolve.
type OperationsClientResolveResponse struct {
// Summary of the subscription
	ResolvedSubscription
}

// OperationsClientUpdateSubscriptionResponse contains the response from method OperationsClient.UpdateSubscription.
type OperationsClientUpdateSubscriptionResponse struct {
// OperationLocationURI contains the information returned from the Operation-Location header response.
	OperationLocationURI *string
}

// SubscriptionOperationsClientGetOperationStatusResponse contains the response from method SubscriptionOperationsClient.GetOperationStatus.
type SubscriptionOperationsClientGetOperationStatusResponse struct {
	SaaSOperation
}

// SubscriptionOperationsClientListOperationsResponse contains the response from method SubscriptionOperationsClient.ListOperations.
type SubscriptionOperationsClientListOperationsResponse struct {
	OperationList
}

// SubscriptionOperationsClientUpdateOperationStatusResponse contains the response from method SubscriptionOperationsClient.UpdateOperationStatus.
type SubscriptionOperationsClientUpdateOperationStatusResponse struct {
	// placeholder for future response values
}

