// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fulfillment

import "time"

type AADIdentifier struct {
	EmailID *string
	ObjectID *string
	Puid *string
	TenantID *string
}

type InternalServerErrorResponse struct {
	Error *InternalServerErrorResponseError
}

type InternalServerErrorResponseError struct {
	Code *string
	Message *string
}

type MeteringDimension struct {
	Currency *string
	DisplayName *string
	ID *string
	PricePerUnit *float32
	UnitOfMeasure *string
}

type MeteringedQuantityIncluded struct {
	DimensionID *string
	Units *string
}

type OperationList struct {
	Operations []*SaaSOperation
}

type Plan struct {
	Description *string
	DisplayName *string
	HasFreeTrials *bool
	IsPricePerSeat *bool
	IsPrivate *bool
	IsStopSell *bool
	Market *string
	MaxQuantity *int64
	MinQuantity *int64
	PlanComponents *PlanComponents
	PlanID *string
	SourceOffers []*SourceOffer
}

type PlanComponents struct {
	MeteringDimensions []*MeteringDimension
	RecurrentBillingTerms []*RecurrentBillingTerm
}

type RecurrentBillingTerm struct {
	Currency *string
	MeteredQuantityIncluded []*MeteringedQuantityIncluded
	Price *float32
	TermDescription *string
	TermUnit *TermUnitEnum
}

// ResolvedSubscription - Summary of the subscription
type ResolvedSubscription struct {
	ID *string
	OfferID *string
	PlanID *string
	Quantity *int64
	Subscription *Subscription
	SubscriptionName *string
}

type SaaSOperation struct {
	Action *OperationActionEnum
	ActivityID *string
	ID *string
	OfferID *string
	PlanID *string
	PublisherID *string
	Quantity *int32
	Status *OperationStatusEnum
	SubscriptionID *string
	TimeStamp *time.Time
}

type SourceOffer struct {
	ExternalID *string
}

type SubscriberPlan struct {
	PlanID *string
	Quantity *int64
}

type Subscription struct {
	AllowedCustomerOperations []*AllowedCustomerOperationsEnum

// Indicating whether the subscription will renew automatically.
	AutoRenew *bool
	Beneficiary *AADIdentifier
	Created *time.Time
	ID *string

// true - the customer subscription is currently in free trial, false - the customer subscription is not currently in free
// trial.(optional field - default false)
	IsFreeTrial *bool

// Indicating whether the current subscription is a test asset.
	IsTest *bool
	Name *string
	OfferID *string
	PlanID *string
	PublisherID *string
	Purchaser *AADIdentifier
	Quantity *int32

// Indicates the status of the operation.
	SaasSubscriptionStatus *SubscriptionStatusEnum

// Possible Values are None, Csp (Csp sandbox purchase)
	SandboxType *SandboxTypeEnum

// Dry Run indicates all transactions run as Test-Mode in the commerce stack
	SessionMode *SessionModeEnum
	Term *SubscriptionTerm
}

type SubscriptionPlans struct {
	Plans []*Plan
}

type SubscriptionTerm struct {
	ChargeDuration *string
	EndDate *time.Time
	StartDate *time.Time
	TermUnit *TermUnitEnum
}

type SubscriptionsResponse struct {
// Link to get the next set of subscriptions.
	NextLink *string
	Subscriptions []*Subscription
}

type UpdateOperation struct {
	PlanID *string
	Quantity *int64
	Status *UpdateOperationStatusEnum
}

