// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fulfillment

import (
	"encoding/json"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"reflect"
)

// MarshalJSON implements the json.Marshaller interface for type AADIdentifier.
func (a AADIdentifier) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "emailId", a.EmailID)
	populate(objectMap, "objectId", a.ObjectID)
	populate(objectMap, "puid", a.Puid)
	populate(objectMap, "tenantId", a.TenantID)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type AADIdentifier.
func (a *AADIdentifier) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", a, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "emailId":
				err = unpopulate(val, "EmailID", &a.EmailID)
			delete(rawMsg, key)
		case "objectId":
				err = unpopulate(val, "ObjectID", &a.ObjectID)
			delete(rawMsg, key)
		case "puid":
				err = unpopulate(val, "Puid", &a.Puid)
			delete(rawMsg, key)
		case "tenantId":
				err = unpopulate(val, "TenantID", &a.TenantID)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", a, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type InternalServerErrorResponse.
func (i InternalServerErrorResponse) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "error", i.Error)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type InternalServerErrorResponse.
func (i *InternalServerErrorResponse) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", i, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "error":
				err = unpopulate(val, "Error", &i.Error)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", i, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type InternalServerErrorResponseError.
func (i InternalServerErrorResponseError) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "code", i.Code)
	populate(objectMap, "message", i.Message)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type InternalServerErrorResponseError.
func (i *InternalServerErrorResponseError) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", i, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "code":
				err = unpopulate(val, "Code", &i.Code)
			delete(rawMsg, key)
		case "message":
				err = unpopulate(val, "Message", &i.Message)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", i, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type MeteringDimension.
func (m MeteringDimension) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "currency", m.Currency)
	populate(objectMap, "displayName", m.DisplayName)
	populate(objectMap, "id", m.ID)
	populate(objectMap, "pricePerUnit", m.PricePerUnit)
	populate(objectMap, "unitOfMeasure", m.UnitOfMeasure)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type MeteringDimension.
func (m *MeteringDimension) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", m, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "currency":
				err = unpopulate(val, "Currency", &m.Currency)
			delete(rawMsg, key)
		case "displayName":
				err = unpopulate(val, "DisplayName", &m.DisplayName)
			delete(rawMsg, key)
		case "id":
				err = unpopulate(val, "ID", &m.ID)
			delete(rawMsg, key)
		case "pricePerUnit":
				err = unpopulate(val, "PricePerUnit", &m.PricePerUnit)
			delete(rawMsg, key)
		case "unitOfMeasure":
				err = unpopulate(val, "UnitOfMeasure", &m.UnitOfMeasure)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", m, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type MeteringedQuantityIncluded.
func (m MeteringedQuantityIncluded) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "dimensionId", m.DimensionID)
	populate(objectMap, "units", m.Units)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type MeteringedQuantityIncluded.
func (m *MeteringedQuantityIncluded) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", m, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "dimensionId":
				err = unpopulate(val, "DimensionID", &m.DimensionID)
			delete(rawMsg, key)
		case "units":
				err = unpopulate(val, "Units", &m.Units)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", m, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type OperationList.
func (o OperationList) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "operations", o.Operations)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type OperationList.
func (o *OperationList) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", o, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "operations":
				err = unpopulate(val, "Operations", &o.Operations)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", o, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Plan.
func (p Plan) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "description", p.Description)
	populate(objectMap, "displayName", p.DisplayName)
	populate(objectMap, "hasFreeTrials", p.HasFreeTrials)
	populate(objectMap, "isPricePerSeat", p.IsPricePerSeat)
	populate(objectMap, "isPrivate", p.IsPrivate)
	populate(objectMap, "isStopSell", p.IsStopSell)
	populate(objectMap, "market", p.Market)
	populate(objectMap, "maxQuantity", p.MaxQuantity)
	populate(objectMap, "minQuantity", p.MinQuantity)
	populate(objectMap, "planComponents", p.PlanComponents)
	populate(objectMap, "planId", p.PlanID)
	populate(objectMap, "sourceOffers", p.SourceOffers)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Plan.
func (p *Plan) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", p, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "description":
				err = unpopulate(val, "Description", &p.Description)
			delete(rawMsg, key)
		case "displayName":
				err = unpopulate(val, "DisplayName", &p.DisplayName)
			delete(rawMsg, key)
		case "hasFreeTrials":
				err = unpopulate(val, "HasFreeTrials", &p.HasFreeTrials)
			delete(rawMsg, key)
		case "isPricePerSeat":
				err = unpopulate(val, "IsPricePerSeat", &p.IsPricePerSeat)
			delete(rawMsg, key)
		case "isPrivate":
				err = unpopulate(val, "IsPrivate", &p.IsPrivate)
			delete(rawMsg, key)
		case "isStopSell":
				err = unpopulate(val, "IsStopSell", &p.IsStopSell)
			delete(rawMsg, key)
		case "market":
				err = unpopulate(val, "Market", &p.Market)
			delete(rawMsg, key)
		case "maxQuantity":
				err = unpopulate(val, "MaxQuantity", &p.MaxQuantity)
			delete(rawMsg, key)
		case "minQuantity":
				err = unpopulate(val, "MinQuantity", &p.MinQuantity)
			delete(rawMsg, key)
		case "planComponents":
				err = unpopulate(val, "PlanComponents", &p.PlanComponents)
			delete(rawMsg, key)
		case "planId":
				err = unpopulate(val, "PlanID", &p.PlanID)
			delete(rawMsg, key)
		case "sourceOffers":
				err = unpopulate(val, "SourceOffers", &p.SourceOffers)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", p, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type PlanComponents.
func (p PlanComponents) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "meteringDimensions", p.MeteringDimensions)
	populate(objectMap, "recurrentBillingTerms", p.RecurrentBillingTerms)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type PlanComponents.
func (p *PlanComponents) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", p, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "meteringDimensions":
				err = unpopulate(val, "MeteringDimensions", &p.MeteringDimensions)
			delete(rawMsg, key)
		case "recurrentBillingTerms":
				err = unpopulate(val, "RecurrentBillingTerms", &p.RecurrentBillingTerms)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", p, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type RecurrentBillingTerm.
func (r RecurrentBillingTerm) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "currency", r.Currency)
	populate(objectMap, "meteredQuantityIncluded", r.MeteredQuantityIncluded)
	populate(objectMap, "price", r.Price)
	populate(objectMap, "termDescription", r.TermDescription)
	populate(objectMap, "termUnit", r.TermUnit)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type RecurrentBillingTerm.
func (r *RecurrentBillingTerm) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", r, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "currency":
				err = unpopulate(val, "Currency", &r.Currency)
			delete(rawMsg, key)
		case "meteredQuantityIncluded":
				err = unpopulate(val, "MeteredQuantityIncluded", &r.MeteredQuantityIncluded)
			delete(rawMsg, key)
		case "price":
				err = unpopulate(val, "Price", &r.Price)
			delete(rawMsg, key)
		case "termDescription":
				err = unpopulate(val, "TermDescription", &r.TermDescription)
			delete(rawMsg, key)
		case "termUnit":
				err = unpopulate(val, "TermUnit", &r.TermUnit)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", r, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type ResolvedSubscription.
func (r ResolvedSubscription) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "id", r.ID)
	populate(objectMap, "offerId", r.OfferID)
	populate(objectMap, "planId", r.PlanID)
	populate(objectMap, "quantity", r.Quantity)
	populate(objectMap, "subscription", r.Subscription)
	populate(objectMap, "subscriptionName", r.SubscriptionName)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type ResolvedSubscription.
func (r *ResolvedSubscription) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", r, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "id":
				err = unpopulate(val, "ID", &r.ID)
			delete(rawMsg, key)
		case "offerId":
				err = unpopulate(val, "OfferID", &r.OfferID)
			delete(rawMsg, key)
		case "planId":
				err = unpopulate(val, "PlanID", &r.PlanID)
			delete(rawMsg, key)
		case "quantity":
				err = unpopulate(val, "Quantity", &r.Quantity)
			delete(rawMsg, key)
		case "subscription":
				err = unpopulate(val, "Subscription", &r.Subscription)
			delete(rawMsg, key)
		case "subscriptionName":
				err = unpopulate(val, "SubscriptionName", &r.SubscriptionName)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", r, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SaaSOperation.
func (s SaaSOperation) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "action", s.Action)
	populate(objectMap, "activityId", s.ActivityID)
	populate(objectMap, "id", s.ID)
	populate(objectMap, "offerId", s.OfferID)
	populate(objectMap, "planId", s.PlanID)
	populate(objectMap, "publisherId", s.PublisherID)
	populate(objectMap, "quantity", s.Quantity)
	populate(objectMap, "status", s.Status)
	populate(objectMap, "subscriptionId", s.SubscriptionID)
	populateDateTimeRFC3339(objectMap, "timeStamp", s.TimeStamp)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SaaSOperation.
func (s *SaaSOperation) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "action":
				err = unpopulate(val, "Action", &s.Action)
			delete(rawMsg, key)
		case "activityId":
				err = unpopulate(val, "ActivityID", &s.ActivityID)
			delete(rawMsg, key)
		case "id":
				err = unpopulate(val, "ID", &s.ID)
			delete(rawMsg, key)
		case "offerId":
				err = unpopulate(val, "OfferID", &s.OfferID)
			delete(rawMsg, key)
		case "planId":
				err = unpopulate(val, "PlanID", &s.PlanID)
			delete(rawMsg, key)
		case "publisherId":
				err = unpopulate(val, "PublisherID", &s.PublisherID)
			delete(rawMsg, key)
		case "quantity":
				err = unpopulate(val, "Quantity", &s.Quantity)
			delete(rawMsg, key)
		case "status":
				err = unpopulate(val, "Status", &s.Status)
			delete(rawMsg, key)
		case "subscriptionId":
				err = unpopulate(val, "SubscriptionID", &s.SubscriptionID)
			delete(rawMsg, key)
		case "timeStamp":
				err = unpopulateDateTimeRFC3339(val, "TimeStamp", &s.TimeStamp)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SourceOffer.
func (s SourceOffer) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "externalId", s.ExternalID)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SourceOffer.
func (s *SourceOffer) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "externalId":
				err = unpopulate(val, "ExternalID", &s.ExternalID)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SubscriberPlan.
func (s SubscriberPlan) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "planId", s.PlanID)
	populate(objectMap, "quantity", s.Quantity)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SubscriberPlan.
func (s *SubscriberPlan) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "planId":
				err = unpopulate(val, "PlanID", &s.PlanID)
			delete(rawMsg, key)
		case "quantity":
				err = unpopulate(val, "Quantity", &s.Quantity)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type Subscription.
func (s Subscription) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "allowedCustomerOperations", s.AllowedCustomerOperations)
	populate(objectMap, "autoRenew", s.AutoRenew)
	populate(objectMap, "beneficiary", s.Beneficiary)
	populateDateTimeRFC3339(objectMap, "created", s.Created)
	populate(objectMap, "id", s.ID)
	populate(objectMap, "isFreeTrial", s.IsFreeTrial)
	populate(objectMap, "isTest", s.IsTest)
	populate(objectMap, "name", s.Name)
	populate(objectMap, "offerId", s.OfferID)
	populate(objectMap, "planId", s.PlanID)
	populate(objectMap, "publisherId", s.PublisherID)
	populate(objectMap, "purchaser", s.Purchaser)
	populate(objectMap, "quantity", s.Quantity)
	populate(objectMap, "saasSubscriptionStatus", s.SaasSubscriptionStatus)
	populate(objectMap, "sandboxType", s.SandboxType)
	populate(objectMap, "sessionMode", s.SessionMode)
	populate(objectMap, "term", s.Term)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type Subscription.
func (s *Subscription) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "allowedCustomerOperations":
				err = unpopulate(val, "AllowedCustomerOperations", &s.AllowedCustomerOperations)
			delete(rawMsg, key)
		case "autoRenew":
				err = unpopulate(val, "AutoRenew", &s.AutoRenew)
			delete(rawMsg, key)
		case "beneficiary":
				err = unpopulate(val, "Beneficiary", &s.Beneficiary)
			delete(rawMsg, key)
		case "created":
				err = unpopulateDateTimeRFC3339(val, "Created", &s.Created)
			delete(rawMsg, key)
		case "id":
				err = unpopulate(val, "ID", &s.ID)
			delete(rawMsg, key)
		case "isFreeTrial":
				err = unpopulate(val, "IsFreeTrial", &s.IsFreeTrial)
			delete(rawMsg, key)
		case "isTest":
				err = unpopulate(val, "IsTest", &s.IsTest)
			delete(rawMsg, key)
		case "name":
				err = unpopulate(val, "Name", &s.Name)
			delete(rawMsg, key)
		case "offerId":
				err = unpopulate(val, "OfferID", &s.OfferID)
			delete(rawMsg, key)
		case "planId":
				err = unpopulate(val, "PlanID", &s.PlanID)
			delete(rawMsg, key)
		case "publisherId":
				err = unpopulate(val, "PublisherID", &s.PublisherID)
			delete(rawMsg, key)
		case "purchaser":
				err = unpopulate(val, "Purchaser", &s.Purchaser)
			delete(rawMsg, key)
		case "quantity":
				err = unpopulate(val, "Quantity", &s.Quantity)
			delete(rawMsg, key)
		case "saasSubscriptionStatus":
				err = unpopulate(val, "SaasSubscriptionStatus", &s.SaasSubscriptionStatus)
			delete(rawMsg, key)
		case "sandboxType":
				err = unpopulate(val, "SandboxType", &s.SandboxType)
			delete(rawMsg, key)
		case "sessionMode":
				err = unpopulate(val, "SessionMode", &s.SessionMode)
			delete(rawMsg, key)
		case "term":
				err = unpopulate(val, "Term", &s.Term)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SubscriptionPlans.
func (s SubscriptionPlans) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "plans", s.Plans)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SubscriptionPlans.
func (s *SubscriptionPlans) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "plans":
				err = unpopulate(val, "Plans", &s.Plans)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SubscriptionTerm.
func (s SubscriptionTerm) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "chargeDuration", s.ChargeDuration)
	populateDateTimeRFC3339(objectMap, "endDate", s.EndDate)
	populateDateTimeRFC3339(objectMap, "startDate", s.StartDate)
	populate(objectMap, "termUnit", s.TermUnit)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SubscriptionTerm.
func (s *SubscriptionTerm) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "chargeDuration":
				err = unpopulate(val, "ChargeDuration", &s.ChargeDuration)
			delete(rawMsg, key)
		case "endDate":
				err = unpopulateDateTimeRFC3339(val, "EndDate", &s.EndDate)
			delete(rawMsg, key)
		case "startDate":
				err = unpopulateDateTimeRFC3339(val, "StartDate", &s.StartDate)
			delete(rawMsg, key)
		case "termUnit":
				err = unpopulate(val, "TermUnit", &s.TermUnit)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type SubscriptionsResponse.
func (s SubscriptionsResponse) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "@nextLink", s.NextLink)
	populate(objectMap, "subscriptions", s.Subscriptions)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SubscriptionsResponse.
func (s *SubscriptionsResponse) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", s, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "@nextLink":
				err = unpopulate(val, "NextLink", &s.NextLink)
			delete(rawMsg, key)
		case "subscriptions":
				err = unpopulate(val, "Subscriptions", &s.Subscriptions)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", s, err)
		}
	}
	return nil
}

// MarshalJSON implements the json.Marshaller interface for type UpdateOperation.
func (u UpdateOperation) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]any)
	populate(objectMap, "planId", u.PlanID)
	populate(objectMap, "quantity", u.Quantity)
	populate(objectMap, "status", u.Status)
	return json.Marshal(objectMap)
}

// UnmarshalJSON implements the json.Unmarshaller interface for type UpdateOperation.
func (u *UpdateOperation) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", u, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "planId":
				err = unpopulate(val, "PlanID", &u.PlanID)
			delete(rawMsg, key)
		case "quantity":
				err = unpopulate(val, "Quantity", &u.Quantity)
			delete(rawMsg, key)
		case "status":
				err = unpopulate(val, "Status", &u.Status)
			delete(rawMsg, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", u, err)
		}
	}
	return nil
}

func populate(m map[string]any, k string, v any) {
	if v == nil {
		return
	} else if azcore.IsNullValue(v) {
		m[k] = nil
	} else if !reflect.ValueOf(v).IsNil() {
		m[k] = v
	}
}

func unpopulate(data json.RawMessage, fn string, v any) error {
	if data == nil || string(data) == "null" {
		return nil
	}
	if err := json.Unmarshal(data, v); err != nil {
		return fmt.Errorf("struct field %s: %v", fn, err)
	}
	return nil
}

