// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.


package metering

const (
	moduleName = "github.com/fastah/azuremarketplacesaas/metering"
	moduleVersion = "v0.11.0"
)

