// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package metering

// APIVersion - The request must send the following parameters as a URL Encoded form; granttype - clientcredentials; resource
// - 20e940b3-4c77-4b0b-9a53-9e16a1b010a7; clientid - AAD Registered App Client ID; client
// secret - AAD Registered App Client Secret
type APIVersion string

const (
	APIVersionTwoThousandEighteen0831 APIVersion = "2018-08-31"
)

// PossibleAPIVersionValues returns the possible values for the APIVersion const type.
func PossibleAPIVersionValues() []APIVersion {
	return []APIVersion{	
		APIVersionTwoThousandEighteen0831,
	}
}

// ReconStatusEnum - Reconcilliation status of the submitted meter.
type ReconStatusEnum string

const (
	ReconStatusEnumAccepted ReconStatusEnum = "Accepted"
	ReconStatusEnumMismatch ReconStatusEnum = "Mismatch"
	ReconStatusEnumRejected ReconStatusEnum = "Rejected"
	ReconStatusEnumSubmitted ReconStatusEnum = "Submitted"
)

// PossibleReconStatusEnumValues returns the possible values for the ReconStatusEnum const type.
func PossibleReconStatusEnumValues() []ReconStatusEnum {
	return []ReconStatusEnum{	
		ReconStatusEnumAccepted,
		ReconStatusEnumMismatch,
		ReconStatusEnumRejected,
		ReconStatusEnumSubmitted,
	}
}

// UsageEventStatusEnum - Status of the operation.
type UsageEventStatusEnum string

const (
	UsageEventStatusEnumAccepted UsageEventStatusEnum = "Accepted"
	UsageEventStatusEnumBadArgument UsageEventStatusEnum = "BadArgument"
	UsageEventStatusEnumDuplicate UsageEventStatusEnum = "Duplicate"
	UsageEventStatusEnumError UsageEventStatusEnum = "Error"
	UsageEventStatusEnumExpired UsageEventStatusEnum = "Expired"
	UsageEventStatusEnumInvalidDimension UsageEventStatusEnum = "InvalidDimension"
	UsageEventStatusEnumInvalidQuantity UsageEventStatusEnum = "InvalidQuantity"
	UsageEventStatusEnumResourceNotActive UsageEventStatusEnum = "ResourceNotActive"
	UsageEventStatusEnumResourceNotAuthorized UsageEventStatusEnum = "ResourceNotAuthorized"
	UsageEventStatusEnumResourceNotFound UsageEventStatusEnum = "ResourceNotFound"
)

// PossibleUsageEventStatusEnumValues returns the possible values for the UsageEventStatusEnum const type.
func PossibleUsageEventStatusEnumValues() []UsageEventStatusEnum {
	return []UsageEventStatusEnum{	
		UsageEventStatusEnumAccepted,
		UsageEventStatusEnumBadArgument,
		UsageEventStatusEnumDuplicate,
		UsageEventStatusEnumError,
		UsageEventStatusEnumExpired,
		UsageEventStatusEnumInvalidDimension,
		UsageEventStatusEnumInvalidQuantity,
		UsageEventStatusEnumResourceNotActive,
		UsageEventStatusEnumResourceNotAuthorized,
		UsageEventStatusEnumResourceNotFound,
	}
}

