// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package metering

// OperationsClientGetUsageEventResponse contains the response from method OperationsClient.GetUsageEvent.
type OperationsClientGetUsageEventResponse struct {
// Array of GetUsageEvent
	GetUsageEventArray []*GetUsageEvent
}

// OperationsClientPostBatchUsageEventResponse contains the response from method OperationsClient.PostBatchUsageEvent.
type OperationsClientPostBatchUsageEventResponse struct {
	BatchUsageEventOkResponse
}

// OperationsClientPostUsageEventResponse contains the response from method OperationsClient.PostUsageEvent.
type OperationsClientPostUsageEventResponse struct {
	UsageEventOkResponse
}

