// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package metering

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"time"
)

// OperationsClient contains the methods for the MeteringOperations group.
// Don't use this type directly, use a constructor function instead.
type OperationsClient struct {
	internal *azcore.Client
	endpoint string
}

// GetUsageEvent - You can call the usage events API to get the list of usage events.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2018-08-31
//   - usageStartDate - DateTime in ISO8601 format. For example, 2020-12-03T15:00 or 2020-12-03.
//   - options - OperationsClientGetUsageEventOptions contains the optional parameters for the OperationsClient.GetUsageEvent
//     method.
func (client *OperationsClient) GetUsageEvent(ctx context.Context, usageStartDate time.Time, options *OperationsClientGetUsageEventOptions) (OperationsClientGetUsageEventResponse, error) {
	var err error
	req, err := client.getUsageEventCreateRequest(ctx, usageStartDate, options)
	if err != nil {
		return OperationsClientGetUsageEventResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return OperationsClientGetUsageEventResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return OperationsClientGetUsageEventResponse{}, err
	}
	resp, err := client.getUsageEventHandleResponse(httpResp)
	return resp, err
}

// getUsageEventCreateRequest creates the GetUsageEvent request.
func (client *OperationsClient) getUsageEventCreateRequest(ctx context.Context, usageStartDate time.Time, options *OperationsClientGetUsageEventOptions) (*policy.Request, error) {
	urlPath := "/usageEvents"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.UsageEndDate != nil {
		reqQP.Set("UsageEndDate", options.UsageEndDate.Format(time.RFC3339Nano))
	}
	reqQP.Set("api-version", "2018-08-31")
	if options != nil && options.AzureSubscriptionID != nil {
		reqQP.Set("azureSubscriptionId", *options.AzureSubscriptionID)
	}
	if options != nil && options.Dimension != nil {
		reqQP.Set("dimension", *options.Dimension)
	}
	if options != nil && options.OfferID != nil {
		reqQP.Set("offerId", *options.OfferID)
	}
	if options != nil && options.PlanID != nil {
		reqQP.Set("planId", *options.PlanID)
	}
	if options != nil && options.ReconStatus != nil {
		reqQP.Set("reconStatus", string(*options.ReconStatus))
	}
	reqQP.Set("usageStartDate", usageStartDate.Format(time.RFC3339Nano))
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.CorrelationID != nil {
		req.Raw().Header["x-ms-correlationid"] = []string{*options.CorrelationID}
	}
	if options != nil && options.RequestID != nil {
		req.Raw().Header["x-ms-requestid"] = []string{*options.RequestID}
	}
	return req, nil
}

// getUsageEventHandleResponse handles the GetUsageEvent response.
func (client *OperationsClient) getUsageEventHandleResponse(resp *http.Response) (OperationsClientGetUsageEventResponse, error) {
	result := OperationsClientGetUsageEventResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.GetUsageEventArray); err != nil {
		return OperationsClientGetUsageEventResponse{}, err
	}
	return result, nil
}

// PostBatchUsageEvent - The batch usage event API allows you to emit usage events for more than one purchased entity at once.
// The batch usage event request references the metering services dimension defined by the publisher
// when publishing the offer.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2018-08-31
//   - options - OperationsClientPostBatchUsageEventOptions contains the optional parameters for the OperationsClient.PostBatchUsageEvent
//     method.
func (client *OperationsClient) PostBatchUsageEvent(ctx context.Context, body BatchUsageEvent, options *OperationsClientPostBatchUsageEventOptions) (OperationsClientPostBatchUsageEventResponse, error) {
	var err error
	req, err := client.postBatchUsageEventCreateRequest(ctx, body, options)
	if err != nil {
		return OperationsClientPostBatchUsageEventResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return OperationsClientPostBatchUsageEventResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return OperationsClientPostBatchUsageEventResponse{}, err
	}
	resp, err := client.postBatchUsageEventHandleResponse(httpResp)
	return resp, err
}

// postBatchUsageEventCreateRequest creates the PostBatchUsageEvent request.
func (client *OperationsClient) postBatchUsageEventCreateRequest(ctx context.Context, body BatchUsageEvent, options *OperationsClientPostBatchUsageEventOptions) (*policy.Request, error) {
	urlPath := "/batchUsageEvent"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2018-08-31")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.CorrelationID != nil {
		req.Raw().Header["x-ms-correlationid"] = []string{*options.CorrelationID}
	}
	if options != nil && options.RequestID != nil {
		req.Raw().Header["x-ms-requestid"] = []string{*options.RequestID}
	}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
	return nil, err
}
;	return req, nil
}

// postBatchUsageEventHandleResponse handles the PostBatchUsageEvent response.
func (client *OperationsClient) postBatchUsageEventHandleResponse(resp *http.Response) (OperationsClientPostBatchUsageEventResponse, error) {
	result := OperationsClientPostBatchUsageEventResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.BatchUsageEventOkResponse); err != nil {
		return OperationsClientPostBatchUsageEventResponse{}, err
	}
	return result, nil
}

// PostUsageEvent - Posts a single usage event to the marketplace metering service API.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2018-08-31
//   - options - OperationsClientPostUsageEventOptions contains the optional parameters for the OperationsClient.PostUsageEvent
//     method.
func (client *OperationsClient) PostUsageEvent(ctx context.Context, body UsageEvent, options *OperationsClientPostUsageEventOptions) (OperationsClientPostUsageEventResponse, error) {
	var err error
	req, err := client.postUsageEventCreateRequest(ctx, body, options)
	if err != nil {
		return OperationsClientPostUsageEventResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return OperationsClientPostUsageEventResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return OperationsClientPostUsageEventResponse{}, err
	}
	resp, err := client.postUsageEventHandleResponse(httpResp)
	return resp, err
}

// postUsageEventCreateRequest creates the PostUsageEvent request.
func (client *OperationsClient) postUsageEventCreateRequest(ctx context.Context, body UsageEvent, options *OperationsClientPostUsageEventOptions) (*policy.Request, error) {
	urlPath := "/usageEvent"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2018-08-31")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.CorrelationID != nil {
		req.Raw().Header["x-ms-correlationid"] = []string{*options.CorrelationID}
	}
	if options != nil && options.RequestID != nil {
		req.Raw().Header["x-ms-requestid"] = []string{*options.RequestID}
	}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
	return nil, err
}
;	return req, nil
}

// postUsageEventHandleResponse handles the PostUsageEvent response.
func (client *OperationsClient) postUsageEventHandleResponse(resp *http.Response) (OperationsClientPostUsageEventResponse, error) {
	result := OperationsClientPostUsageEventResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.UsageEventOkResponse); err != nil {
		return OperationsClientPostUsageEventResponse{}, err
	}
	return result, nil
}

